import Nav from "./components/Nav";
import Providers from "./components/Providers";
import "./globals.css";
import "./cyberpunk.css";

export const metadata = {
    title: "Portfolio | Nassim",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <Providers>
                    <Nav />
                    <main className="w-full min-h-screen bg-black-pearl">
                        {children}
                    </main>
                </Providers>
            </body>
        </html>
    );
}
